[package]
name = "beam-bvm-interface"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
bindgen = "0.53.1"